---
image: bazarr
version: v0.8.24
name: Bazarr
description: "[Bazarr](https://www.bazarr.media/) is a companion application to Sonarr and Radarr. It can manage and download subtitles based on your requirements. You define your preferences by TV show or movie and Bazarr takes care of everything for you."
ext_release: "v1.5.4"
arch:
  - aarch64
  - x86_64
